#!/usr/bin/env python
'''
AWS Information Script - Dan P
Search for amazon instance by ID, Name tag or IP ip_address
The boto python library will look for credentials matching each profile in ~/.aws/credentials file
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
'''
import sys
import boto.ec2
import re
import os
import ConfigParser
import pickle
from threading import Thread


profile = None
regions = None
cache_file = None

all_instances = []

def print_line(k, v):
    print "{0}:\t{1}".format(k,v)


def find_instance_from(search_field, search_string):

    all_instances = get_all_servers_from_cache_file()
    instance = filter(lambda instance: instance[search_field] == search_string, all_instances)

    if not instance:
        print "Not Found. Consider running a refresh if you think this is a mistake"
        sys.exit(0)
    elif len(instance) > 1:
        print_multiple_warning(instance)
        sys.exit()
    else:
        return instance[0]


def print_multiple_warning(instances):
    print "More than one instance found, use a different field to be more precise"
    for instance in instances:
        print_instance_info(instance)


def print_instance_info(instance):
    print ''
    print_line('Name', instance['name'])
    print_line('Acc', instance['acc'])
    print_line('AZ', instance['az'])
    print_line('ID', instance['id'])
    print_line('IP', instance['ip'])
    print_line('Type', instance['type'])
    print_line('State', instance['state'])
    print_line('Key', instance['key'])
    print_line('DNS', instance['dns'])
    print ''


def open_ssh_session(instance):
    ssh_key_path = "{}/.ssh/{}.pem".format(os.path.expanduser("~"), instance['key'])
    if instance['state'] == 'running':
        if os.path.isfile(ssh_key_path):
            try:
                raw_input('Press enter to continue...\n')
                os.system('ssh -o StrictHostKeyChecking=no -i {} ec2-user@{}'.format(ssh_key_path, instance['ip']))
            except KeyboardInterrupt:
                print "Cancelled"
        else:
            print "ERROR: ssh key {} not found".format(ssh_key_path)


def print_usage():
    print "usage {} [refresh|i-12345|54.32.10.01|Live Web Server 01]".format(os.path.basename(__file__))


def load_config():
    global profiles
    global regions
    global cache_file

    config_file = '~/.awsi/config.cfg'

    if not os.path.exists(os.path.expanduser(config_file)):
        print "ERROR: missing config file " + config_file
        sys.exit(1)

    config = ConfigParser.ConfigParser()
    config.read(os.path.expanduser(config_file))
    regions = config.get('main','regions').split(',')
    profiles = config.get('main','profiles').split(',')
    cache_file = config.get('main','cache_file')


def retrieve_servers_from_aws_account(profile):
    global all_instances

    for region in regions:
        print "[re]caching {0} {1}".format(profile, region)
        conn = boto.ec2.connect_to_region(region, profile_name=profile)
        instances = [
            instance
            for reservations in conn.get_all_instances()
            for instance in reservations.instances
        ]
        for instance in instances:
            all_instances.append({
                "id":instance.id,
                "name": instance.tags.get('Name', None),
                "ip":instance.ip_address,
                "acc":profile,
                "az":instance.placement,
                "type":instance.instance_type,
                "state":instance.state,
                "key":instance.key_name,
                "dns":instance.public_dns_name
            })
        conn.close()


def refresh_cache():
    global all_instances
    threads = []
    try:
        for profile in profiles:
            t = Thread(name="Thread-{}".format(profile), target=retrieve_servers_from_aws_account, args=(profile,))
            t.start()
            threads.append(t)

        for t in threads:
            t.join()

        with open(cache_file, 'w') as f:
            pickle.dump(all_instances, f)

        print "Cache written to {}".format(cache_file)
    except Exception as e:
        print e.message
        sys.exit(1)
    except KeyboardInterrupt:
        print "Cancelled"
    except boto.provider.ProfileNotFoundError:
        print "profile '{}' not found in aws config".format(profile)


def get_all_servers_from_cache_file():
    try:
        with open(cache_file, 'r') as f:
            return pickle.load(f)
    except IOError as e:
        print e
        print "Cache file not found, run awsi refresh to generate it"
        sys.exit(1)


def print_cache():
    for server in get_all_servers_from_cache_file():
        print server['name']


if __name__ == '__main__':

    arg = ' '.join(sys.argv[1:])
    
    ip_re = re.compile('^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$')
    id_re = re.compile('^i-.{8}$')

    if not arg:
        print_usage()
        sys.exit()

    load_config()

    if os.path.basename(__file__) == 'awssh':
        __ssh_session = True

    if "refresh" == arg:
        refresh_cache()
        sys.exit()

    if "list" == arg:
        print_cache()
        sys.exit()

    connect_to_instance = None

    if ip_re.match(arg):
        connect_to_instance = find_instance_from("ip", arg)
    elif id_re.match(arg):
        connect_to_instance = find_instance_from("id", arg)
    else:
        connect_to_instance = find_instance_from("name", arg)

    print_instance_info(connect_to_instance)
    open_ssh_session(connect_to_instance)
